## Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [1]:
import numpy as np 
arr  = np.array([1,2,4,5,8,6,4,4,4])
x =  np.where(arr == 4)
print (x)

(array([2, 6, 7, 8], dtype=int64),)


### indexes where the values are even:

In [15]:
arr1 = np.arange(100,200)
evens= []
odds= []
even_no= 0
odd_no= 0
for x in arr1:
    if x % 2 ==0:
         evens.append(x)
         even_no = even_no+1
    else:
         odds.append(x)
         odd_no +=1
         

print(evens)
print(even_no)
print(odds)
print(odd_no)
print(type(evens))
print(type(arr1))

y = np.where(arr1%2 == 0)
print(y)

[100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
50
[101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]
50
<class 'list'>
<class 'numpy.ndarray'>
(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98],
      dtype=int64),)


## Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.


In [24]:
import numpy as np
arr = np.array([1,2,3,5,7,9,48])
x = np.searchsorted(arr,4)

print(x)

3


## Search From the Right Side

In [26]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


## Multiple Values

In [27]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]
