### Random Numbers in NumPy

#### Pseudo Random and True Random.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.



#### Generate Random Number

In [3]:
from numpy import random

x = random.randint(1000)
print(x)

623


## Generate Random Float
The random module's rand() method returns a random float between 0 and 1.

In [31]:
import numpy
x = random.rand( )# generate a number from 0 - 1
print(x)

0.5918558721289183


In [32]:
x = random.randint(100, size = (3,5))
print(x)

[[36 98 67 76 97]
 [21 30 50 31 32]
 [33 42 92 91 10]]


In [61]:
from numpy import random
x = random.choice([3,5,6,5,8,"kj"]) # choose the random number from the list
print(x)

8


In [64]:
x = random.choice([4,7,8,9,6,8] , size = (3,8)) # generate a 3 row and 8 columns
print(x)

[[8 4 9 8 7 9 9 4]
 [4 8 6 6 9 7 8 6]
 [6 6 8 8 6 9 4 8]]
